<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="AWSSDK.SimpleEmail" Version="4.0.1.1" />
    <PackageReference Include="Google.Apis.Auth" Version="1.68.0" />
    <PackageReference Include="Google.Cloud.Firestore" Version="3.9.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.1" />
    <PackageReference Include="MimeKit" Version="4.13.0" />
    <PackageReference Include="Quartz" Version="3.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dominio\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTO\OutputDto\Post\" />
    <Folder Include="DTO\Register\ExistUserEmail\" />
    <Folder Include="DTO\Register\Register\" />
    <Folder Include="Interfaces\Firebase\" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Aplication.ResponPattern;" />
    <Using Include="MediatR" />
  </ItemGroup>

</Project>
